version: "3"
services:
  hub:
    image: testimage:latest
    restart: always
    environment:
      - BROWSER=${BROWSER}
      - CONCURRENCY=${CONCURRENCY}
    volumes:
      - /Users/sritaj/TechnicalKnowHow/JavaScriptUIAutomationTools/TestCafe/TestCafe_DockerResults:/app/test-artifacts/
